### PR TITLE
Exception policies + defaults rather than swallowing

### PR DESCRIPTION
**Pull request by haf**
Hiya,

Review, see what u think.

Henrik

### CODE REVIEW

**Comment by haf** [comment]
No attention; closing.

**Comment by ragnard** [comment]
Hi Henrik,

Sorry for not giving this pull request the attention it deserves.

I'm no longer using Graphite.NET (or .NET in general) and I don't have the time or resources to maintain it. If you're interested in taking over, please get in touch.

As for the patch, it looks great technically, but I'm not convinced the added complexity is warranted for something like sending metrics to Graphite, but I guess it depends on how important you consider it to be to not lose any data points. Also, since the calls to send data to Graphite are currently blocking, adding retries, with delays etc. will potentially have an impact on the duration of the original web service call. This may be OK, depending on your priorities, but it's a tradeoff worth discussing. If I wanted retries etc, I would probably make the WCF interceptor put all graphite messages on a queue, and process the queue in a separate thread.

Cheers,

Ragnar

**Comment by haf** [comment]
Hi,

I haven't used this lib much after my pull reqeuest. Any new stuff I'm doing is likely to use either RabbitMQ or ZeroMQ as a message-interface to Logstash, where I can then transform and handle data, like such:
http://blog.pkhamre.com/2012/07/05/visualizing-logdata-with-logstash-statsd-and-graphite/

I disagree that it is complected; it's still simple, but with added features. There is no extra/further branching to have to consider when reading the code. Whether you consider it a feature to block on network 'more than for the first failure' or not, is up to you as a programmer -- I would probably rewrite this as a leaky-bucket based actor in F# with async TCP, async RabbitMQ/publisher-confirms or ZMQ, if I were really aiming to create a library for sending to Graphite for .Net.

Or it could be interesting to send tagged log lines into NLog, so that I don't have to care about yet another interface.

Anyway, thanks for getting back to me.

For curiosity, what are you working with now?

**Comment by ragnard** [comment]
Hey,

Thanks for the link, I think the metrics-in-logs approach is interesting, I've toyed a bit with Nimrod (https://github.com/sbtourist/nimrod) which you might be familiar with.

I completely agree that I as a library writer should not decide or limit how you want to handle failures in your application. How about making the exception policy stuff a library that you could use when invoking any operation and opening up the WCF stuff in this library to allow such extensions?

In practice, I'm not really sure what to do with this now when neither of us are really using it. In fact, I don't even have a VS install to build this stuff and push it to nuget, so I guess the best I can do is wait and see if someone wishes to take over... or until the library self-deprecates and dies.

I moved to the UK a while ago and now I'm working for uswitch.com doing mostly Clojure. Great fun, great people.

Thanks for your contribution and the interesting discussion, much appreciated.

**Pull request closed without merging**
